services:
  postgres:
    image: postgres:latest
    container_name: Postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: nhomec123
      POSTGRES_DB: ecommerce_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
        - ./Repository/data_log/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"